services:
  mysql:
    container_name: container-bd-treetech
    image: treetechnology/imagem-bd-treetech:v1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: TreeTechnology
    volumes:
      - db_data:/var/lib/mysql
      - ./arquivos_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - treetech-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  node:
    container_name: container-node-treetech
    image: treetechnology/imagem-node-treetech:v2
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:80"
    networks:
      - treetech-network

  java:
    container_name: container-java-treetech
    image: treetechnology/imagem-java-treetech:v2
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - treetech-network
    environment:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

volumes:
  db_data:

networks:
  treetech-network:
    driver: bridge
